language: node_js
env:
  - NODE_ENV='test'
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules
before_install:
  - nvm install 8
install:
  - npm install
script:
  - npm test
matrix:
  include:
    - language: objective-c
      os: osx
      script:
        - cd ios && xcodebuild -scheme RCTAlipay -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -derivedDataPath build
    - language: android
      os: linux
      jdk: oraclejdk8
      android:
        components:
          - build-tools-23.0.1
          - android-23
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      script:
        - cd android && ./gradlew build
