matrix:
  include:
    - language: objective-c
      os: osx
      # osx_image: xcode9
      cache: yarn
      before_install:
        - nvm install 7
        - npm install -g yarn
      install:
        - yarn
      script:
        - cd ios && xcodebuild -scheme RCTAlipay -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -derivedDataPath build
    - language: android
      os: linux
      jdk: oraclejdk8
      android:
        components:
          - build-tools-23.0.1
          - android-23
      cache: yarn
      before_install:
        - nvm install 7
        - npm install -g yarn
      install:
        - yarn
      script:
        - cd android && ./gradlew build
